name: Windows build

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Check out repository 
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10
        
    - name: Install
      run: pip install tox

    - name: Build
      run: tox
      
    - uses: actions/upload-artifact@v3
      with:
        name: SerialPortIdentifier.exe
        path: dist/SerialPortIdentifier.exe
